[book]
title = "The ikigai Book"
authors = ["Brian Sletten"]
language = "en"
src = "src"

[output.html]
default-theme = "rust"
git-repository-url = "https://github.com/ikigai-rs/ikigai-tutorial"
edit-url-template = "https://github.com/ikigai-rs/ikigai-tutorial/edit/main/books/ikigai/{path}"
additional-css = []

[output.html.fold]
enable = true
level = 1

[rust]
edition = "2021"
